############################################################################
##                                                                        ##
##     Questa pipeline non e' sincronizzata con Terraform cloud, ma       ##
##     e' possibile riprodurre questo workflow anche li'. Link:           ##
##     https://learn.hashicorp.com/tutorials/terraform/github-actions     ##    
##                                                                        ##
############################################################################

name: Terraform destroy [master]

on: 
  workflow_dispatch:
    branches: [ master]

jobs: 
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init --backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" --backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Terraform Validate
        run: terraform validate -no-color
      - name: Terraform Plan
        run: terraform plan -no-color
        env:
          TF_VAR_AWS_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_RDS_USER: ${{ secrets.RDS_USERNAME }}
          TF_VAR_RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          TF_VAR_RDS_PORT: ${{ secrets.RDS_PORT }}
          TF_VAR_RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_AWS_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_RDS_USER: ${{ secrets.RDS_USERNAME }}
          TF_VAR_RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          TF_VAR_RDS_PORT: ${{ secrets.RDS_PORT }}
          TF_VAR_RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}

        




